export const dummyAccounts = [
  {
    extension: "200",
    account_type: "SIP(WebRTC)",
    fullname: "200 Simon",
    out_of_service: "no",
    status: "Idle",
    addr: "192.168.80.200:44147 (GRP2615)",
    urgemsg: 0,
    newmsg: 0,
    oldmsg: 0,
    lockflag: 0,
    presence_status: "available",
    presence_def_script: "",
    user_name: "200",
    email_to_user: "no",
  },
  {
    extension: "201",
    account_type: "SIP(WebRTC)",
    fullname: "201 Jacqui",
    out_of_service: "no",
    status: "Idle",
    addr: "192.168.80.201:5060 (GXP2170)",
    urgemsg: 0,
    newmsg: 0,
    oldmsg: 0,
    lockflag: 0,
    presence_status: "available",
    presence_def_script: "",
    user_name: "201",
    email_to_user: "no",
  },
  {
    extension: "202",
    account_type: "SIP(WebRTC)",
    fullname: "202 Louis",
    out_of_service: "no",
    status: "Idle",
    addr: "192.168.80.29:32915 (GRP2670)",
    urgemsg: 0,
    newmsg: 0,
    oldmsg: 0,
    lockflag: 0,
    presence_status: "available",
    presence_def_script: "",
    user_name: "202",
    email_to_user: "no",
  },
  {
    extension: "203",
    account_type: "SIP(WebRTC)",
    fullname: "203 Louis Home",
    out_of_service: "no",
    status: "Unavailable",
    addr: "-",
    urgemsg: 0,
    newmsg: 0,
    oldmsg: 0,
    lockflag: 0,
    presence_status: "available",
    presence_def_script: "",
    user_name: "203",
    email_to_user: "no",
  },
  {
    extension: "204",
    account_type: "SIP(WebRTC)",
    fullname: "204 Spare Desk",
    out_of_service: "no",
    status: "Idle",
    addr: "192.168.80.21:5060 (GXP2160)",
    urgemsg: 0,
    newmsg: 0,
    oldmsg: 0,
    lockflag: 0,
    presence_status: "available",
    presence_def_script: "",
    user_name: "204",
    email_to_user: "no",
  },
  {
    extension: "205",
    account_type: "SIP(WebRTC)",
    fullname: "205 Office Meeting Room",
    out_of_service: "no",
    status: "Idle",
    addr: "192.168.80.202:43881 (GRP2614)",
    urgemsg: 0,
    newmsg: 0,
    oldmsg: 0,
    lockflag: 0,
    presence_status: "available",
    presence_def_script: "",
    user_name: "205",
    email_to_user: "no",
  },
  {
    extension: "206",
    account_type: "SIP(WebRTC)",
    fullname: "206 Office Wifi",
    out_of_service: "no",
    status: "Idle",
    addr: "192.168.80.18:5060 (WP820)",
    urgemsg: 0,
    newmsg: 0,
    oldmsg: 0,
    lockflag: 0,
    presence_status: "available",
    presence_def_script: "",
    user_name: "206",
    email_to_user: "no",
  },
  {
    extension: "207",
    account_type: "SIP(WebRTC)",
    fullname: "207 Wave Test",
    out_of_service: "no",
    status: "Unavailable",
    addr: "-",
    urgemsg: 0,
    newmsg: 0,
    oldmsg: 0,
    lockflag: 0,
    presence_status: "available",
    presence_def_script: "",
    user_name: "207",
    email_to_user: "no",
  },
  {
    extension: "208",
    account_type: "SIP(WebRTC)",
    fullname: "",
    out_of_service: "no",
    status: "Unavailable",
    addr: "-",
    urgemsg: 0,
    newmsg: 0,
    oldmsg: 0,
    lockflag: 0,
    presence_status: "available",
    presence_def_script: "",
    user_name: "208",
    email_to_user: "no",
  },
  {
    extension: "210",
    account_type: "SIP(WebRTC)",
    fullname: "210 Office Speaker",
    out_of_service: "no",
    status: "Idle",
    addr: "192.168.80.210:5060 (GSC3510)",
    urgemsg: 0,
    newmsg: 0,
    oldmsg: 0,
    lockflag: 0,
    presence_status: "available",
    presence_def_script: "",
    user_name: "210",
    email_to_user: "no",
  },
  {
    extension: "220",
    account_type: "SIP(WebRTC)",
    fullname: "220 Simon SOL",
    out_of_service: "no",
    status: "Unavailable",
    addr: "-",
    urgemsg: 0,
    newmsg: 0,
    oldmsg: 0,
    lockflag: 0,
    presence_status: "available",
    presence_def_script: "",
    user_name: "220",
    email_to_user: "no",
  },
  {
    extension: "221",
    account_type: "SIP(WebRTC)",
    fullname: "221 Jonathan SOL",
    out_of_service: "no",
    status: "Idle",
    addr: "192.168.40.202:5062 (GXP2160)",
    urgemsg: 0,
    newmsg: 0,
    oldmsg: 0,
    lockflag: 0,
    presence_status: "available",
    presence_def_script: "",
    user_name: "221",
    email_to_user: "no",
  },
  {
    extension: "222",
    account_type: "SIP(WebRTC)",
    fullname: "222 Jonathan Home",
    out_of_service: "no",
    status: "Idle",
    addr: "80.229.219.91:48200 (GXP2160)",
    urgemsg: 0,
    newmsg: 0,
    oldmsg: 0,
    lockflag: 0,
    presence_status: "available",
    presence_def_script: "",
    user_name: "222",
    email_to_user: "no",
  },
  {
    extension: "223",
    account_type: "SIP(WebRTC)",
    fullname: "223 Jonathan Prestbury",
    out_of_service: "no",
    status: "Idle",
    addr: "212.56.92.89:63430 (GXP2160)",
    urgemsg: 0,
    newmsg: 0,
    oldmsg: 0,
    lockflag: 0,
    presence_status: "available",
    presence_def_script: "",
    user_name: "223",
    email_to_user: "no",
  },
  {
    extension: "224",
    account_type: "SIP(WebRTC)",
    fullname: "224 Jonathan Prestbury Tech",
    out_of_service: "no",
    status: "Unavailable",
    addr: "-",
    urgemsg: 0,
    newmsg: 0,
    oldmsg: 0,
    lockflag: 0,
    presence_status: "available",
    presence_def_script: "",
    user_name: "224",
    email_to_user: "no",
  },
  {
    extension: "230",
    account_type: "SIP(WebRTC)",
    fullname: "230 France WIFI",
    out_of_service: "no",
    status: "Idle",
    addr: "192.168.85.200:5060 (WP820)",
    urgemsg: 0,
    newmsg: 0,
    oldmsg: 0,
    lockflag: 0,
    presence_status: "available",
    presence_def_script: "",
    user_name: "230",
    email_to_user: "no",
  },
  {
    extension: "231",
    account_type: "SIP(WebRTC)",
    fullname: "231 France WIFI 2",
    out_of_service: "no",
    status: "Idle",
    addr: "192.168.85.13:5060 (WP820)",
    urgemsg: 0,
    newmsg: 0,
    oldmsg: 0,
    lockflag: 0,
    presence_status: "available",
    presence_def_script: "",
    user_name: "231",
    email_to_user: "no",
  },
  {
    extension: "250",
    account_type: "SIP(WebRTC)",
    fullname: "250 HOME DOWN",
    out_of_service: "no",
    status: "Idle",
    addr: "192.168.81.220:5060 (WP820)",
    urgemsg: 0,
    newmsg: 0,
    oldmsg: 0,
    lockflag: 0,
    presence_status: "available",
    presence_def_script: "",
    user_name: "250",
    email_to_user: "no",
  },
  {
    extension: "251",
    account_type: "SIP(WebRTC)",
    fullname: "251 HOME UP",
    out_of_service: "no",
    status: "Idle",
    addr: "192.168.81.204:5060 (WP820)",
    urgemsg: 0,
    newmsg: 0,
    oldmsg: 0,
    lockflag: 0,
    presence_status: "available",
    presence_def_script: "",
    user_name: "251",
    email_to_user: "no",
  },
  {
    extension: "299",
    account_type: "SIP(WebRTC)",
    fullname: "Mobile Mode",
    out_of_service: "no",
    status: "Unavailable",
    addr: "-",
    urgemsg: 0,
    newmsg: 0,
    oldmsg: 0,
    lockflag: 0,
    presence_status: "available",
    presence_def_script: "",
    user_name: "299",
    email_to_user: "no",
  },
];

export const dummyExtensionGet = {
  extension: {
    account_type: "SIP(WebRTC)",
    fullname: "202 Louis",
    hasvoicemail: "no",
    cidnumber: "",
    enable_fecc: 0,
    vmsecret: "15598",
    skip_vmsecret: "no",
    ring_timeout: "",
    auto_record: "external",
    encryption: "no",
    faxdetect: "no",
    fax_gateway: "no",
    sendtofax: "yes",
    strategy_ipacl: 1,
    enable_fec: 1,
    enable_video_fec: 1,
    enable_rtx_nack: 0,
    local_network1: "192.168.80.0",
    local_network2: "192.168.81.0",
    local_network3: "",
    local_network4: "",
    local_network5: "",
    local_network6: "",
    local_network7: "",
    local_network8: "",
    local_network9: "",
    local_network10: "",
    specific_ip: "",
    allow: "ulaw,alaw,gsm,g726,g722,g729,h264,ilbc",
    dnd: "no",
    im_dnd: "no",
    dnd_timetype: 0,
    permission: "internal-local-national",
    nat: "yes",
    bypass_outrt_auth: "no",
    skip_auth_timetype: 0,
    t38_udptl: "no",
    directmedia: "no",
    dtmfmode: "rfc4733",
    enable_qualify: "no",
    qualify: 1000,
    qualifyfreq: 60,
    authid: "",
    tel_uri: "disabled",
    enablehotdesk: "no",
    user_outrt_passwd: "",
    out_of_service: "no",
    mohsuggest: "default",
    cc_agent_policy: "never",
    cc_monitor_policy: "never",
    cc_max_agents: 1,
    cc_max_monitors: 2,
    en_ringboth: "no",
    external_number: "",
    use_callee_dod_on_fwd_rb: "no",
    use_callee_dod_on_fm: "no",
    ringboth_timetype: 0,
    enable_ldap: "yes",
    max_contacts: 6,
    custom_autoanswer: "no",
    presence_def_script: "",
    sca_enable: "no",
    call_waiting: "yes",
    emergcidnumber: "",
    jitter_buffer: "disable",
    jbmpl: "fixed",
    jblen: 100,
    jbmax: 100,
    mohforivr_enable: "no",
    out_maxchans: 0,
    cancel_others_if_one_reject: "no",
    srtp_suite: "AES_CM_128_HMAC_SHA1_80",
    presence_status: "available",
    enable_webrtc: "yes",
    use_avpf: "yes",
    ice_support: "yes",
    media_encryption: "auto_dtls",
    intranet_ip_filter: "no",
    alertinfo: "",
    limitime: "",
    fwdwhitelist: "",
    highfreq_duration: "",
    highfreq_num: "",
    missed_call: "no",
    missed_call_type: "",
    callbarging_monitor: "",
    seamless_transfer_members: "",
    pms_whitelist_members: "",
    dndwhitelist: "",
    extension: "202",
    secret: "s*76qz209U",
  },
  sip_presence_settings: [
    {
      presence_status: "available",
      cfb: "",
      cfn: "",
      cfu: "",
      cfb_timetype: 0,
      cfn_timetype: 0,
      cfu_timetype: 0,
      cfb_destination_type: "0",
      cfn_destination_type: "0",
      cfu_destination_type: "0",
    },
    {
      presence_status: "away",
      cfb: "",
      cfn: "",
      cfu: "",
      cfb_timetype: 0,
      cfn_timetype: 0,
      cfu_timetype: 0,
      cfb_destination_type: "0",
      cfn_destination_type: "0",
      cfu_destination_type: "0",
    },
    {
      presence_status: "chat",
      cfb: "",
      cfn: "",
      cfu: "",
      cfb_timetype: 0,
      cfn_timetype: 0,
      cfu_timetype: 0,
      cfb_destination_type: "0",
      cfn_destination_type: "0",
      cfu_destination_type: "0",
    },
    {
      presence_status: "unavailable",
      cfb: "",
      cfn: "",
      cfu: "",
      cfb_timetype: 0,
      cfn_timetype: 0,
      cfu_timetype: 0,
      cfb_destination_type: "0",
      cfn_destination_type: "0",
      cfu_destination_type: "0",
    },
    {
      presence_status: "userdef",
      cfb: "",
      cfn: "",
      cfu: "",
      cfb_timetype: 0,
      cfn_timetype: 0,
      cfu_timetype: 0,
      cfb_destination_type: "0",
      cfn_destination_type: "0",
      cfu_destination_type: "0",
    },
  ],
  cti_feature_privilege: {
    extension_status: "no",
    active_call: "no",
    hangup: "no",
    callbarge: "no",
  },
  voicemail: {
    vm_attach: "",
    vm_reserve: "",
    vm_sendmail: "no",
  },
};

export const dummyExtGroup = {
  extension_group: [
    {
      group_id: "group-1",
      group_name: "Extension_group_1",
      members: "200,201,202,205",
      tmp: "group-1",
    },
    {
      group_id: "group-2",
      group_name: "Extension_group_2",
      members: "224,223,222",
      tmp: "group-2",
    },
    {
      group_id: "group-3",
      group_name: "Old_extGroup",
      members: "230,231,250,251",
      tmp: "group-3",
    },
  ],
};
